apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webls
    spec:
      containers:
      - image: gcr.io/assignment2-205312/web:v1
        name: web
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 8080
      restartPolicy: Always
